/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.GameCall
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ObjInfo : TBase
  {
    private sbyte _Type;
    private int _ObjPtr;
    private int _ID;
    private int _EnemyID;
    private int _HP;
    private int _MaxHP;
    private int _Level;
    private int _X;
    private int _Y;
    private int _Color;
    private List<sbyte> _Name;
    private List<sbyte> _TypeName;

    public sbyte Type
    {
      get
      {
        return _Type;
      }
      set
      {
        __isset.Type = true;
        this._Type = value;
      }
    }

    public int ObjPtr
    {
      get
      {
        return _ObjPtr;
      }
      set
      {
        __isset.ObjPtr = true;
        this._ObjPtr = value;
      }
    }

    public int ID
    {
      get
      {
        return _ID;
      }
      set
      {
        __isset.ID = true;
        this._ID = value;
      }
    }

    public int EnemyID
    {
      get
      {
        return _EnemyID;
      }
      set
      {
        __isset.EnemyID = true;
        this._EnemyID = value;
      }
    }

    public int HP
    {
      get
      {
        return _HP;
      }
      set
      {
        __isset.HP = true;
        this._HP = value;
      }
    }

    public int MaxHP
    {
      get
      {
        return _MaxHP;
      }
      set
      {
        __isset.MaxHP = true;
        this._MaxHP = value;
      }
    }

    public int Level
    {
      get
      {
        return _Level;
      }
      set
      {
        __isset.Level = true;
        this._Level = value;
      }
    }

    public int X
    {
      get
      {
        return _X;
      }
      set
      {
        __isset.X = true;
        this._X = value;
      }
    }

    public int Y
    {
      get
      {
        return _Y;
      }
      set
      {
        __isset.Y = true;
        this._Y = value;
      }
    }

    public int Color
    {
      get
      {
        return _Color;
      }
      set
      {
        __isset.Color = true;
        this._Color = value;
      }
    }

    public List<sbyte> Name
    {
      get
      {
        return _Name;
      }
      set
      {
        __isset.Name = true;
        this._Name = value;
      }
    }

    public List<sbyte> TypeName
    {
      get
      {
        return _TypeName;
      }
      set
      {
        __isset.TypeName = true;
        this._TypeName = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Type;
      public bool ObjPtr;
      public bool ID;
      public bool EnemyID;
      public bool HP;
      public bool MaxHP;
      public bool Level;
      public bool X;
      public bool Y;
      public bool Color;
      public bool Name;
      public bool TypeName;
    }

    public ObjInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Byte) {
              Type = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              ObjPtr = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              ID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              EnemyID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              HP = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              MaxHP = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              Level = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I32) {
              X = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.I32) {
              Y = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              Color = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.List) {
              {
                Name = new List<sbyte>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  sbyte _elem6 = 0;
                  _elem6 = iprot.ReadByte();
                  Name.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.List) {
              {
                TypeName = new List<sbyte>();
                TList _list7 = iprot.ReadListBegin();
                for( int _i8 = 0; _i8 < _list7.Count; ++_i8)
                {
                  sbyte _elem9 = 0;
                  _elem9 = iprot.ReadByte();
                  TypeName.Add(_elem9);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ObjInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.Type) {
        field.Name = "Type";
        field.Type = TType.Byte;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Type);
        oprot.WriteFieldEnd();
      }
      if (__isset.ObjPtr) {
        field.Name = "ObjPtr";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ObjPtr);
        oprot.WriteFieldEnd();
      }
      if (__isset.ID) {
        field.Name = "ID";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ID);
        oprot.WriteFieldEnd();
      }
      if (__isset.EnemyID) {
        field.Name = "EnemyID";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(EnemyID);
        oprot.WriteFieldEnd();
      }
      if (__isset.HP) {
        field.Name = "HP";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(HP);
        oprot.WriteFieldEnd();
      }
      if (__isset.MaxHP) {
        field.Name = "MaxHP";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MaxHP);
        oprot.WriteFieldEnd();
      }
      if (__isset.Level) {
        field.Name = "Level";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Level);
        oprot.WriteFieldEnd();
      }
      if (__isset.X) {
        field.Name = "X";
        field.Type = TType.I32;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(X);
        oprot.WriteFieldEnd();
      }
      if (__isset.Y) {
        field.Name = "Y";
        field.Type = TType.I32;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Y);
        oprot.WriteFieldEnd();
      }
      if (__isset.Color) {
        field.Name = "Color";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Color);
        oprot.WriteFieldEnd();
      }
      if (Name != null && __isset.Name) {
        field.Name = "Name";
        field.Type = TType.List;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Byte, Name.Count));
          foreach (sbyte _iter10 in Name)
          {
            oprot.WriteByte(_iter10);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (TypeName != null && __isset.TypeName) {
        field.Name = "TypeName";
        field.Type = TType.List;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Byte, TypeName.Count));
          foreach (sbyte _iter11 in TypeName)
          {
            oprot.WriteByte(_iter11);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ObjInfo(");
      sb.Append("Type: ");
      sb.Append(Type);
      sb.Append(",ObjPtr: ");
      sb.Append(ObjPtr);
      sb.Append(",ID: ");
      sb.Append(ID);
      sb.Append(",EnemyID: ");
      sb.Append(EnemyID);
      sb.Append(",HP: ");
      sb.Append(HP);
      sb.Append(",MaxHP: ");
      sb.Append(MaxHP);
      sb.Append(",Level: ");
      sb.Append(Level);
      sb.Append(",X: ");
      sb.Append(X);
      sb.Append(",Y: ");
      sb.Append(Y);
      sb.Append(",Color: ");
      sb.Append(Color);
      sb.Append(",Name: ");
      sb.Append(Name);
      sb.Append(",TypeName: ");
      sb.Append(TypeName);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
